### ISSUE TITLE
Morphic: Gradient fills?

### ISSUE THREAD

**Issue by darth-cheney** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#113]
Is there any way to perform gradient fills on a Morph (rectangular or otherwise)?

**Comment by samis** [comment]
You might be better off asking the mailing list. http://cuis-smalltalk.org/mailman/listinfo/cuis-dev_cuis-smalltalk.org.

**Comment by jvuletich** [comment]
Yes. In the Messages Names tool just look for "gradient". You will find (amongst others) #verticalGradient:topColor:bottomColor: . It has two examples in the method comment.

**Comment by darth-cheney** [comment]
Ok thanks. I see that this is a straight vertical only gradient (meaning it doesn't have the capability to do diagonal), but I think I should be able to implement something like that by relying on this code here.
