### ISSUE TITLE
Feature require: 'StyledTextInstaller' seems to fail because of Color.

### ISSUE THREAD

**Issue by matt-00** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#120]
I did:
```
$ cd Cuis-Smalltalk-Dev/
$ git checkout fffecef
$ cd ..
$ Squeak.app/Contents/MacOS/Squeak Cuis-Smalltalk-Dev/Cuis5.0-3117.image
```

fffecef

Then, in a workspace: 
`Feature require: 'StyledTextInstaller'`

I got:
![screen shot 2017-06-26 at 23 09 17](https://user-images.githubusercontent.com/29636644/27560551-e4e84864-5ac4-11e7-890e-47a8bab56d79.png)

**Comment by jvuletich** [comment]
This is now fixed. Thanks for the report.
