### ISSUE TITLE
Empty ByteArray literals don't parse

### ISSUE THREAD

**Issue by afairy** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#125]
I was loading WebClient on 3129 which contains
```smalltalk
a ReadStream 'close
	"Send a close control request"

	closing ifFalse:[
		closing := true.
		self send: #[] code: 8.
	].'
```
I fails while trying to parse the empty literal. Try evaluating `#[].` in a workspace to reproduce. Either this or I'm doing something weird :-) . This is on macOS Sierra.

Maybe related to a57d9e6f7c63919bcf1e080f6c5a86f50c86f8d8

**Comment by jvuletich** [comment]
Yes. (as you know) it is already fixed. Thanks for the report!
