### ISSUE TITLE
Code editors should use Monospaced font by default

### ISSUE THREAD

**Issue by edcrypt** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#128]
Loving Cuis. Only a small thing that bothers me, is that code is shown in a variable width font.

**Comment by jvuletich** [comment]
Could be done... But we currently don't include any monospaced font in the image, so it is a rather big job. Most of us got used to variable with fonts...

**Comment by jvuletich** [comment]
Ok. Good news. Update your image up to #3188. See AdditionalFontData/Readme.txt
There you are! Monospaced font for Cuis.
