### ISSUE TITLE
Error in OpenCLError class errorStringForCode:

### ISSUE THREAD

**Issue by PuercoPop** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#134]
When the errorCode is not found the default error message to returned is composed using 

```
do: ['INVALID ERROR CODE (', errCode, ')!!!'].`
```
However errCode is a number, so sending to appendToString: to a SmallInteger fails. One fix would be to convert the error code to a string, ie.

```
^[errorNames at: errCode negated] on: Error do: ['INVALID ERROR CODE (', errCode asString, ')!!!'].
```

**Comment by jvuletich** [comment]
Fixed. Thank you!
