### ISSUE TITLE
The download of Cuis

### ISSUE THREAD

**Issue by no-e-in** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#138]
The download of Cuis-Smalltalk-Dev-master.zip is 101 MB. Is it possible to have a release version of Cuis?

**Comment by jvuletich** [comment]
Thanks for bringing this up. Truth is that many of the biggest files in the repo were not really part of the Cuis Smalltalk distribution, but historical stuff. I moved them to https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Historical . Now the download zip is 25 MB, including 3 flavors of the image (v3, spur32 and spur64).
