### ISSUE TITLE
Options on a laptop with a QHD screen?

### ISSUE THREAD

**Issue by elbow** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#146]
Hi,

Is their a way to get Cuis Smalltalk to scale up the whole screen 2x - my laptop has a QHD screen so Cuis renders very tiny.  

I can change font sizes etc but the nett effect is rather weird with still microscopic window decorations etc.

Thanks,
Steve

**Comment by jvuletich** [comment]
Hi Steve, just close and reopen any windows after the change, and decorations will be scaled too.

Cheers,
Juan Vuletich

**Comment by elbow** [comment]
Thanks, it does help.

I see the haloes are still very tiny, and is there a way to get fonts bigger than the "Huge" size?

Regards,
Steve

**Comment by jvuletich** [comment]
I' ve just added support for some larger sizes for fonts and GUI elements.

pull from Git
Start Cuis
Install New Updates
in ./AdditionalFontData, expand DejaVuSansLarge.zip
evaluate `StrikeFont install: 'DejaVu'.`
Chose one of the new huge font sizes.

#biggerCursors works by crudely enlarging existing 16x16 cursors, except for the NormalCursor (the arrow mouse pointer) that was redone. Building a complete set of large, nice looking cursors with alpha masks would be a nice thing.
