### ISSUE TITLE
ColorForm stroreString

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#169]
This code `(Form fromFileNamed: 'subMenu.png') storeString `

subMenu.png: ![subMenu](https://user-images.githubusercontent.com/1217542/83744678-c32e1280-a65c-11ea-9d9b-487cf5a25cbd.png)

produces this executable statement, but it executes as a very different funny Form
```
((ColorForm
	extent: 9@6
	depth: 2
	fromArray: #( 87381 109225 27300 6800 1600 256)
	offset: 0@0)
	colorsFromArray: #(#( ) #(0.000 0.000 0.000) #(0.063 0.808 0.325) #( )  ))
```

Tested with 4200 change set

**Comment by jvuletich** [comment]
Fix at GitHub. Thanks for the report.
