### ISSUE TITLE
WebClient not working

### ISSUE THREAD

**Issue by mmontone** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#171]
WebClient points to some Monticello code that does not make sense in Cuis, and WebClient doesn't work.

https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/61973629fe5855267df6479040e9b2d03eae02a9/Packages/Features/WebClient.pck.st#L8529

What to do?

**Comment by mmontone** [comment]
I think we can remove the references to mcVersion method and construct the UserAgent without it

https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/61973629fe5855267df6479040e9b2d03eae02a9/Packages/Features/WebClient.pck.st#L3948

**Comment by nmingotti** [comment]
As of today the following works
```
Feature require: 'WebClient'. 
(WebClient httpGet:'http://www.google.com') content.
```
I would close this issue. It is true there is a reference to Monticello, but seems harmless.

**Comment by jvuletich** [comment]
I assume it works correctly now.
