### ISSUE TITLE
Rampant background paint errors

### ISSUE THREAD

**Issue by singpolyma** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#173]
I cloned everything according to instructions, and ran the image on the squeak VM available in Debian stable (squeak-vm version 4.10.2.2614 looks like).

Things seem to work well, except that there is no background and nothing is ever unpainted.  Even using the "restore display" menu item does nothing.  So when I close a window it still shows until a new window is put atop it, which can be quite confusing.

Is this likely to be a bug in my VM or something odd in Cuis?  I'm fairly new to the smalltalk world so not really sure where to begin looking...

**Comment by mmontone** [comment]
It is the VM, probably.

Try with another one, as explained here: https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/GettingStarted.md

**Comment by jvuletich** [comment]
I assume that mmontone's comment resolved the issue, after almost a year with no follow up.
