### ISSUE TITLE
Float32PointArray comment

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#176]
In paclage Cuis-Smalltalk-Dev/Packages/System/Collections-CompactArrays.pck.st 

The comment of Float32PointArray should be:

> This class stores points with 32 bit Floating point elements.
> 
> {1@2. 3@4} as: **Float32PointArray**

**Comment by jvuletich** [comment]
Fixed. Thanks!
