### ISSUE TITLE
Inconsistency in Tool instanciation

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#180]
I found this inconsistency when instantiating new Workspace (compare to Browser and Transcript):

```
BrowserWindow openBrowser morphBounds: (0 @ 0 extent: extent).
BrowserWindow openBrowser morphBounds: (area width // 2 @ 0 extent: extent).
BrowserWindow openBrowser morphBounds: (area extent // 2 extent: extent).
Workspace openWorkspace.
TranscriptWindow openTranscript morphBounds: 
	(0 @ (area height // 2 + (2 / 3 * extent y)) 
		extent: extent x @ (1 / 3 * extent y )).
```

The way Workspace is created is also annoying because you can't access its view. I can't programmatically open a workspace where I want in the world.

**Comment by jvuletich** [comment]
Just pushed an update to make #openWorkspace answer the Window. Now, these work the same:
BrowserWindow openBrowser morphPosition: 100@100 extent: 600@400.
Workspace openWorkspace morphPosition: 100@100 extent: 600@400.
TranscriptWindow openTranscript morphPosition: 100@100 extent: 600@400.
