### ISSUE TITLE
updateUpButtonImage

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#183]
Several methods implemented in the **PluggableButtonMorph** seems to be use only in **ScrollBar**:
It is **updateUpButtonImage**, **updateRightButtonImage**, **updateLeftButtonImage**, **updateDownButtonImage**

This is odd.

**Comment by jvuletich** [comment]
Refactored, and fixed a recent bug. Thanks.
