### ISSUE TITLE
OSProcess / SqueakCompatibility

### ISSUE THREAD

**Issue by rd--** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#186]
hello

(i sent this to the -dev list also, but it may not get through since i'm not a member...)

i'm very new to cuis, it look's nice so far!

i'm writing because typing:

    Feature require: 'OSProcess'

gives an error, it fails to locate "SqueakCompatibility"

i see (using gitk) that the file "CompatibilityPackages/SqueakCompatibility.pck.st" was recently deleted

reverting one commit (ie. to reinstate that file) makes the above work

best,
rohan

**Comment by nachoba** [comment]
That package was deleted. I had the same issue with Erudite.
Fortunately I have a copy of the package that solved the issue.

[SqueakCompatibility.pck.zip](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/files/6151017/SqueakCompatibility.pck.zip)

**Comment by rd--** [comment]
hello - thanks for fixing this! - closing - best, rd
