### ISSUE TITLE
Inconcistency between scripts: clone vs pull al repos

### ISSUE THREAD

**Issue by nachoba** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#187]
Hi,
When I run the clonePackageRepos.sh all repos are cloned inside the Cuis-Smalltalk-Dev directory. 
When I try to run the pullAllRepos.sh it assumes that the repos are outside of the Cuis-Smalltalk-Dev folder, which I think is the correct place for them.
I think the script should start with
```bash
#!/bin/bash
cd ..
git clone https://github.com/Cuis-Smalltalk/SVG.git
...
...
```
Cheers
Nacho

**Comment by jvuletich** [comment]
You are right. Just fixed it. Thanks!
