### ISSUE TITLE
Performance drop after loading TrueType fonts on Linux

### ISSUE THREAD

**Issue by moniquelive** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#188]
I’m sorry to make a superficial report but I’m just getting started with smalltalk and Cuis. 
What I’ve noticed is that when I load the TrueType fonts (under preferences menu) the frame rate of the environment drops considerably. 
By observing the process list, the Morphic UI process cpu usage is pegged above 90%.

my distro is Pop OS 20.10 nvidia with all updates.

**Comment by JTurco32** [comment]
Hey moniquelive,
Id thought id chime in, true-type fonts do cause some latency, for what reason i sadly do not know. Ive been told by the devs for my system (raspberry pi) not to enable it. Just thought id let you know its not just you that experiences the lag.

**Comment by jvuletich** [comment]
Some performance penalty is reasonable. If you feel it is excessive, and you are using a VM that includes a functional VectorEnginePlugin, please email https://lists.cuis.st/mailman/listinfo/cuis-dev
