### ISSUE TITLE
VectorCanvas>>ellipseCenter:radius:borderWidth:borderColor:fillColor:

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#189]
message #x unnecessary:

| radiusPoint |
	radiusPoint _ radiusPointOrNumber asPoint.
	self strokeWidth: morphStrokeWidth color: strokeColor fillColor: fillColor do: [
		self ellipseCenter: center **x** radius: radiusPoint ]

**Comment by jvuletich** [comment]
Fixed.
