### ISSUE TITLE
VectorGraphicsAndMorphic3.md needs update

### ISSUE THREAD

**Issue by codefrau** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#192]
This document does not match the current image anymore:

https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/725e6e12be488004e6d0854bf70b9182a73ae04a/Documentation/VectorGraphicsAndMorphic3.md

The menu items have been relabeled, and the DoIt results in an MNU:

```
self runningWorld backgroundImage displayAt: 0@0.
(VectorCanvas onForm: Display) fullDraw: self runningWorld.
Display copy inspect.
```

**Comment by jvuletich** [comment]
I updated the doc, and added some examples and suggestions of things to try. Please take a look!

**Comment by codefrau** [comment]
Looks great!
