### ISSUE TITLE
Running Cuis on BSD systems

### ISSUE THREAD

**Issue by lpvm** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#197]
Would it be possible to make Cuis Smalltalk available to the BSDs operating systems?
At least for FreeBSD and NetBSD.

Thanks.

**Comment by nmingotti** [comment]
hi Luis,

i am doing the debian upgrades. as soon as possible i will tell you how to
do it.

basically, there are 2 roads. the linux compatibility layer or you try the
VM for your os. there should be a bsd version . as far as i remember in
cuis-smalltalk-dev github installation notes there should be something
about it.

will tell more when my laptop is available.

bye
nicola

**Comment by nmingotti** [comment]
So, let's start to collect the pieces.
 
The virtual machine release we use by default in Cuis is this: 
https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/tag/201901172323

There I don't see a BSD binary, but there are sources, try to compile them.

Or, you install in LinuxCompatibility layer and the run it from there.
I was running Squeak like this about 1.5 years ago, in FreeBSD. It worked well. 

let me know ! 
bye

**Comment by nmingotti** [comment]
I answered you on github issues.

Please, see my next mail to the mailing list about github issues.

bye
Nicola

**Comment by nmingotti** [comment]
I tried to compile the VM in OpenBSD recently and I failed. This should be reported in the VM github issue. I will do when time permits.

**Comment by jvuletich** [comment]
This issues should be better discussed at the VM list (1). There are more people there that can help.
(1) http://lists.squeakfoundation.org/mailman3/lists/vm-dev.lists.squeakfoundation.org/
