### ISSUE TITLE
Invoking Do it in a Debugger raises an error

### ISSUE THREAD

**Issue by npapagna** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#220]
**Describe the bug**
`Do it` cannot be used in a Debugger, an error is raised.

**Steps to reproduce**
1. Open a Workspace with `a := 1`.
2. Right-click on the Workspace -> `Debug`
3. Invoke `Do it` on `a := 1`.
4. Notice the following error is raised: `Error: 'subscript is out of bounds: 1'`

**Expected behavior**
I was expecting to be able to use `Do it` in the Debugger.

**Screen captures**
![image](https://user-images.githubusercontent.com/1807185/147853033-4d583830-9507-4348-af21-1276b12790ac.png)

**Additional context**
`Do it` works just fine in a Workspace, the error is raised when trying to invoke it in a Debugger.

**Comment by jvuletich** [comment]
It seems this has been fixed. Thanks!
