### ISSUE TITLE
MNU on StrikeFont >> #cachedFormDepth when trying to load all TrueType fonts on Windows 11

### ISSUE THREAD

**Issue by asampal** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#230]
When I try to load all TrueType fonts, the MNU below pops up (many windows). 

![image](https://user-images.githubusercontent.com/281639/168922359-a2e11503-b459-4ab7-ab84-ba108ac54a2b.png)

**Comment by asampal** [comment]
I think this went away when I used the most recent VM.

**Comment by jvuletich** [comment]
Actually, I fixed it in update 5172. Forgot to update this issue, though. Apologies.
