### ISSUE TITLE
Problems installing dependency PetitParser

### ISSUE THREAD

**Issue by asarch** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#232]
I need this depedency for the MorphicBook and other packages:

![Screenshot from 2022-07-24 17-20-11](https://user-images.githubusercontent.com/906401/180668160-0d10ee5d-3720-45b7-a30c-9deeb6e137a7.png)

however, when I try to download it:

![Screenshot from 2022-07-24 17-20-04](https://user-images.githubusercontent.com/906401/180668185-cadc27c5-80fc-4017-9788-c9cebd8bd4b3.png)

and after several 'Proceed' I get:

![Screenshot from 2022-07-24 17-22-30](https://user-images.githubusercontent.com/906401/180668207-77b0081b-c1f4-48ae-9d42-23c340ee2d7c.png)

**Comment by mmontone** [comment]
SqueakCompatibility package is part of this repository: https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/CompatibilityPackages/SqueakCompatibility.pck.st

and so it should be found if you are using this.

You are using CuisUniversity distribution; it doesn't come with the SqueakCompatibility package perhaps?

**Comment by asarch** [comment]
That's the problem. There is no SqueakCompatibility package.
