### ISSUE TITLE
Poblems upgrading

### ISSUE THREAD

**Issue by asarch** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#233]
Why I can't upgrade?

![Screenshot from 2022-07-25 00-20-48](https://user-images.githubusercontent.com/906401/180704888-5a50ca3e-2fcf-4b16-9e02-75d815e9d8a9.png)

**Comment by jvuletich** [comment]
Hi Asarch, We don't guarantee that any image can be updated, as we don't control the status of your images. I suggest reloading your code into an updated image you can grab from our repo. Additionally, please don't use "Issues" to ask for help. Please use the mail list for that: https://lists.cuis.st/mailman/listinfo/cuis-dev
