### ISSUE TITLE
Halo menues don't work if a menu of the Halo of another object is oppened

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#240]
Halo menues don't work if a menu of the Halo of another object is oppened. In this iimage my mouse is ontop of the menu of the right oject but is does not responds.

![image](https://user-images.githubusercontent.com/845725/206619594-2b3c0e10-2115-4470-a94f-83c97fac8790.png)

I'm running on windows 10, with es-MX as localization and using Cuis 6v 5588.
I also tried before updating the image an before installing anything else.

**Comment by rcpacheco** [comment]
I keept experimenting following these steps and found a combination of actions to reproduce the problem and to solve it:
1) Clone the Cuis-Smalltalk-Dev repo.
2) Clone additional repos.
3) Then I launch the Smalltalk.exe with the image Cuis6.0-5542.image.
4) Maximize window.
5) Close the About Cuis Window & Transcript.
6) Create a BoxedMorp, open its halo and increase its size.
7) Create a LabelMorph, open its halo, then its Menu and increase the font size to 26.
8) Open the LabelMorph halo again, then its Menu and click the right orange pin and move the menu.
9) Open the halo of the BoxedMorph:
    - tried to open the Menu and then the Debug and they both **DON'T WORK**.
    - open the explore window, it opens. Close it.
10) Open the halo of the BoxedMorph again:
    - tried to open the Menu and then the Debug and both **DO WORK !!**

The problem happens wheter the image is updated to current (5588).

I tried also with a Cuis-University Image and got the same behaviour.

**Comment by jvuletich** [comment]
Thanks for the report. Fix is now at GitHub as update #5619.
