### ISSUE TITLE
make #shuffled and #sorted produce same type

### ISSUE THREAD

**Issue by VictorelPetrovich** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#244]
Reading last part of https://cuis-smalltalk.github.io/TheCuisBook/Message-to-string-entities.html , 
"Note that this breaks the pattern of the result type. We get a String result when sending a String the message #shuffled but get an Array result when sending a String the message #sorted."

Why have this inconsistency, if both change the order of character in the string? 

I'd vote for both to produce String result.

**Comment by jvuletich** [comment]
Done. Pull and load latest updates. Thanks for reporting.

**Comment by VictorelPetrovich** [comment]
That was fast! Thank you.
