### ISSUE TITLE
#asciiValue doesn't work for $(20) and $(09)

### ISSUE THREAD

**Issue by VictorelPetrovich** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#245]
In Workspace, with "ctrl+p" or "ctrl+d"

`65 asCharacter.   => $A `
`$A asciiValue.  65 `

Fine; but:
`32 asCharacter.   =>  $ (20)  ` (space)
`$ (20)  asciiValue.  => error: "$ Nothing more expected ->(20)  asciiValue.  "`

`9 asCharacter.   => $ (09) ` (tab)
 `$ (09) asciiValue.  => error: " $ Nothing more expected ->(09) asciiValue.  "`

Is my expectation wrong?

**Comment by jvuletich** [comment]
The printing of an object, in general, is not able to recreate the object. #storeString is used for that. Anyway, I modified the printing of characters to meet your expectation. Pull and load latest updates.

**Comment by VictorelPetrovich** [comment]
OK, thanks!
