### ISSUE TITLE
Browser close on: Sample04Pacman new openInHand 

### ISSUE THREAD

**Issue by rcpacheco** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#246]
With an updated Cuis image (5660) open a Browser and Workspace and enter the text:
Sample04Pacman new openInHand 

Uppon doing click on it, the browser closes

**Comment by rcpacheco** [comment]
![BugPacman](https://user-images.githubusercontent.com/845725/219385385-c6cfa9b0-030b-42a0-accf-235e6f28fe3b.gif)

**Comment by rcpacheco** [comment]
I tried again with Cuis6.0-5671 and got the same result

**Comment by jvuletich** [comment]
It is on purpose. Check the class comment!

**Comment by rcpacheco** [comment]
I read the class documentation and understnd that it will try to "eat" anything. Nevertheless the browser is closed even if Pacman is not near.  Therefore I reported it,
