### ISSUE TITLE
Create missing method from Debugger

### ISSUE THREAD

**Issue by hilaire** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#256]
When there is a MNU error, I observed that the Create button in the debugger creates the #error: method not the missing method

**Comment by hernanwilkinson** [comment]
I could not reproduce the error. It implements the not understood message.
Could you provide more info on the conditions that that happens?

**Comment by jvuletich** [comment]
After 6 months without activity, I assume behavior is correct. Please reopen if needed. Thanks!
