### ISSUE TITLE
NonBooleanReceiver on "browse protocol"

### ISSUE THREAD

**Issue by andrzejp** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#262]
Selecting a class in the System Browser and invoking "browse protocol" (Ctrl-p, etc.) signals NonBooleanReceiver. The selected class does not matter.

<img width="1146" alt="image" src="https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/assets/8323636/8ec69b2d-b271-4abe-9a24-a7f7bc23495c">

**Comment by mnqpr** [comment]
![image](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/assets/97891301/f46aa23f-9cb6-448b-a188-8c999852e364)
This error can be mitigated temporally by addig a nil check to the MessageSet class' shouldAutoHighlight method.
`^ shouldAutoHighlight ifNil: false ifNotNil: shouldAutoHighlight `

**Comment by jvuletich** [comment]
Just pushed a fix. Thanks for reporting!
