### ISSUE TITLE
Key not found error: ProtocolBrowserWindow>>browseVersions

### ISSUE THREAD

**Issue by dram** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#266]
Occasionally, `key not found` error will be raised when browsing versions in `ProtocolBrowserWindow`.

Steps to reproduce:

1. Browse class `Collection`
2. Open Protocol Brower for it
3. Select `-> (Object)`
4. Click `versions` button

`Error: key: #-> not found` will be raised.

Cuis Version: Cuis 6.0 #6034

**Comment by jvuletich** [comment]
Fixed. Thanks for reporting.
