### ISSUE TITLE
Inconsistent Dark Theme window color of Process Browser and Preferences

### ISSUE THREAD

**Issue by dram** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#268]
With Dark Theme enabled, color of Process Browser and Preferences window seems to be inconsistent with others. i.e.:

![image](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/assets/517130/51e0985e-3563-4f20-b089-9f65c45fd5eb)

**Comment by jvuletich** [comment]
Fixed. Thanks for reporting.
