### ISSUE TITLE
FileManTest>>testDefaultDirectory fails if the image isn't in the current directory

### ISSUE THREAD

**Issue by Kirtai** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#269]
If Cuis is started from another directory then the test
```
FileManTest>>testDefaultDirectory 
```
will fail.

This appears to be due to the recent changes in default directories which mean that 
```
'' asDirectoryEntry
```
is no longer the same as 
```
DirectoryEntry currentDirectory
```

**Comment by jvuletich** [comment]
Yes. Thanks so much! I've just reverted the offending change.
