### ISSUE TITLE
SVG requires Color-Extras which seems absent in Cuis6-2

### ISSUE THREAD

**Issue by cstes** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#272]
I'm reporting this issue in 3 places:  Cuis-Smalltalk-Dev, Cuis6-2 and hilaire/drgeo.

I'm following the instructions from hilaire/drgeo which is using Cuis6-2

`git clone https://github.com/Cuis-Smalltalk/Cuis6-2
`
It seems the hilaire/drgeo instructions are based on Cuis6-2 and not on the rolling release 6.3 (Cuis-Smalltalk-Dev).

On Cuis6-2 when I try to load the package SVG (for example using Feature: require:'SVG'') or using the menu with install Package, I get an error:

****Unable to find package Color-Extras****

Now it appears that Color-Extras.pkg.st exists in Cuis 6.3 rolling release under:

**Packages/Features/Color-Extras.pck.st** 

Also the  documentation clearly shows Color-Extras loaded at 9.4 in the Cuis Documentation 

[](https://cuis-smalltalk.github.io/TheCuisBook/The-Package.html
)

https://cuis-smalltalk.github.io/TheCuisBook/The-Package.html

Unfortunately I do not seem to have Color-Extras.pkg.st in Cuis6-2.

Is this a bug in SVG, Cuis6-2, or in Dr-Geo ?  Perhaps it could be argued that Dr-Geo should be using the rolling release Cuis-Smalltalk-Dev (6.3) instead of Cuis 6.2 ??  Or is this a bug in the SVG package ?

Thanks!
David

**Comment by jvuletich** [comment]
The 6.2 Stable Release doesn't include optional packages hosted on other repos. This may improve on forthcoming Stable Releases. WTR how to build DrGeo, pleas contact Hilaire directly or ask in the Cuis mail list.
This issue tracker is for Cuis Rolling Release issues.
