### ISSUE TITLE
drgeo tag 23.12a-beta BrowserWindow doesNotUnderstand openBrowser problem

### ISSUE THREAD

**Issue by cstes** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#273]
It seems that the drgeo repository has a tag called 23.12a-beta which I think is the most recent release of drgeo.

Should this not be a separate git branch please ? I don't see branches, only the main branch, and one git tag.

When I git checkout 23.12q-beta , the README indicates a method to use Cuis-Smalltalk-Dev and the clonePackagesRepo.sh script , which I hope to be able to use for Cuis 6.3 rolling release.

However the startIDE.sh script still points to Cuis6.0-nnnn.image and not a Cuis6.3-nnnn.image

When I use the fileList in Cuis to file in drgeo pkg.st, this seems partly succesful, I am able to run DrGeoSystem beDevelopment after filing in DrGeo.

However I still get a doesNotUnderstand message, this time for BrowserWindow which complains that it has no implementation for the openBrowser message.

So I am unsure I am following the right setup procedure.

There is a tag in Cuis-Smalltalk-Dev called BaseForCuis6.2 which contains the old Cuis6.0-nnnn.image but I'd rather use the Cuis6.3-nnnn.image if possible.

Thanks
David Stes

**Comment by jvuletich** [comment]
This issue tracker is for Cuis issues, not DrGeo. Please contact Hilaire (DrGeo creator) for a better place for this. In any case, the Cuis mail list is an appropriate place for this. But not this issue tracker.
Thanks
