### ISSUE TITLE
Request for V3 image support

### ISSUE THREAD

**Issue by cstes** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#274]
I understand that V3 image support was dropped recently.

In the past, for example when looking at the git tag BaseForCuis6.2 there was a v3 image.

[Cuis6.0-6153-v3.image](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/BaseForCuis6.2/Cuis6.0-6153-v3.image)

This v3 image could be used on platforms with a classical Squeak vm (which was not OpenSmalltalk or Spur based).

Would it please be possible to continue to provide 32bit v3 images or is this request too much work please ?

Please note that from my perspective I still tihnk the old Squeak vm has some good points.

One issue is the support for the SPARC cpu (big endian) which I think is not present in the opensmalltalk VM's.  Another issue is that I submitted/contributed a patch for the classical squeak VM in 2021 for the function sqUnixUtcWithOffset() and the HAVE_TM_GMTOFF issue in the plugins/LocalePlugin/sqLocalePlugin.c  and the convertTosSqueakTime() function.

I'll create a separate issue for that anyhow because I think the OpenSmalltalk VM suffers from a similar (or perhaps different) issue similar to the one that my patch for the subversion sources in 2021 fixed for the classical Squeak VM.

Regards,
David Stes

**Comment by jvuletich** [comment]
Yes. We no longer support V3 images in the rolling release.

For many years Cuis was provided both in V3 and Spur image formats, using exactly the same source code and with full compatibility between them. A few month ago, after discussion in the mail list, we decided that taking full advantage of immediate Unicode Characters was more important than having V3 images. The V3 image format and VMs don't support immediate Characters. So we can no longer use them.

It is not a matter of the amount of work, it is about the evolution of Cuis.

Still, I don't see why the OpenSmalltalk Spur VM couldn't be built for SPARC. I think addressing that would be better.

In any case, you can find the last V3 image as part of the Cuis 6.2 Stable Release: https://github.com/Cuis-Smalltalk/Cuis6-2/tree/main/CuisImage/32BitImages .
