### ISSUE TITLE
DrGeo runs on Cuis 6.3

### ISSUE THREAD

**Issue by cstes** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#276]
Just to report that DrGeo latest release seems to run now on Cuis 6.3 rolling latest release.

There was a special update to CoreUpdates with a file

6279-CuisCore-HilaireFernandes-2024Mar16-17h56m-hlsf.001.cs.st

Nevertheless from the point of view of running older releases of DrGeo I am still interested in loading SVG or Erudite packages in older verisons of Cuis.

**Comment by cstes** [comment]
The nicest part that I have seen so far is running the

DrGSmalltalkSketchEditor

When I evaluate and open the Browser for the DrGSmalltalkSketchEditor it contains a list of examples such as Archimedes PI, Bernouilli, Durer, Fermat, Newton-Raphson and others.

These display very crisp and nicely, I think it is fast, due to the VectorEnginePlugin (are drawings done using SVG ?)  Moving windows around is fast and the VectorEnginePlugin module is loaded (dynamic object file)

**Comment by cstes** [comment]
It's actually DrGSmalltalkSketchBrowser that displays the  list of examples ...

DrGSmalltalkSketchBrowser open:(DrGeoSystem smalltalkSketchesPath) label:'Browse".

**Comment by cstes** [comment]
is the update 6279-CuisCore-HilaireFernandes-2024Mar16-17h56m-hlsf.001.cs.st integrated in Cuis 6.3 rolling latest release please ?

**Comment by jvuletich** [comment]
> is the update 6279-CuisCore-HilaireFernandes-2024Mar16-17h56m-hlsf.001.cs.st integrated in Cuis 6.3 rolling latest release please ?
Was that change set posted to the mail list? If so, please answer to that thread. If not, please ask in the mail list, with an url where to find that change set.
