### ISSUE TITLE
Unable to run Cuis7.1-6452 in Javascript/ECMAscript Squeak.JS

### ISSUE THREAD

**Issue by dcstes** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#287]
Using the latest SqueakJS (Javascript/ECMAScript virtual machine) release 1.2.2 using NodeJS 22.3 as server, and firefox as webbrowser, I can run Cuis succesfully frmo the BaseForCuis6.2 git tag  : running Cuis6.0-6153.image works for me using SqueakJS.

However when I try the same thing with the latest Cuis7.1-6452.image, it seems to have an issue in the method getCurrentWorkingDirectory where it raises an errorNotIndexable String isAscii: method.

Is tihs a SqueakJS vm issue or a Cuis 7.1 issue please ?

**Comment by jvuletich** [comment]
SqueakJS doesn't seem to support 16 bit indexables (DoubleByteArray in Cuis). This is required to run Cuis7.1 and later.

**Comment by dcstes** [comment]
Thank you for your feedback.   I'd like to add that I like Cuis Smalltalk and it's great software.   I use DrGeo and Cuis and it's working fine using the C runtime (the Cog OpenSmalltalk C runtime).   I have created a few simple Smalltalk programs in a repository https://github.com/dcstes/sharygin for DrGeo running on Cuis 7.1.    I created this specific github issue to provide some feedback because I also think the JavaScript/ECMAscript runtime is an impressive product as well.   Please feel free to close this github issue and thanks again for the feedback, and for Cuis Smalltalk.
