### ISSUE TITLE
Collections-CompactArrays.pck.st deleted

### ISSUE THREAD

**Issue by mvolkmann** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#290]
Commit 96984e4 deleted the file `Packages/System/Collections-CompactArrays.pck.st`. Was that intentional?
I believe that is the reason why when I enter `Feature require: 'UI-Tools' in a Workspace and "Do it", I get the following error:

Could not find code package file for [Collections-CompactArrays].
Installation of [UI-Widgets] failed.

**Comment by jvuletich** [comment]
It was removed on purpose. You need to pull the updated https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-UI.
