### ISSUE TITLE
Character codePoint: bug

### ISSUE THREAD

**Issue by mvolkmann** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#292]
The attached fileOut is the simplest class I could create the demonstrates the issue.
I had to add `.txt` to the file name to make GitHub allow me to attach it.
After removing `.txt` from the end and doing a fileIn on it, enter `ArrayKeyBug new openInWorld` in a Workspace and "Do it".
Then move the mouse over the orange `BoxedMorph` that appears and press each of the arrow keys.
This will demonstrate the issues summarized in the attached screenshot.

[ArrowKeyBug.st.txt](https://github.com/user-attachments/files/16487857/ArrowKeyBug.st.txt)
![Screenshot 2024-08-04 at 9 09 54 AM](https://github.com/user-attachments/assets/10bba790-2670-4f07-b08d-1833f954700d)

**Comment by jvuletich** [comment]
I'd say this is more an inconsistence than a bug. In any case, I just pushed updates to make Character and keyboard code consistent.

**Comment by mvolkmann** [comment]
@jvuletich Thanks so much for addressing this!
