### ISSUE TITLE
Sound bug

### ISSUE THREAD

**Issue by thiagoslino** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#297]
> Try :
> 
> ``` Beeper beep ```
> 
> 
> 
> Result:
> 
>  MNU SystemDictionary>>newExternalSemaphoreDo: 

 _Originally posted by @thiagoslino in [0d4be5c](https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/commit/0d4be5c69720693587226d5c4374931061714300#r148332399)_

**Comment by jvuletich** [comment]
Fixed. Thanks for reporting!
