### ISSUE TITLE
question about proportionalWidth/proportionalHeight sizing difference in horizontal layout

### ISSUE THREAD

**Issue by davidedc** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#30]
(same question applies for symmetric case of vertical layout)

Basically:
- if I add morphs as "proportionalWidth" in an horizontal layout, then the elements' width is proportional _to each other_, such that the morphs fill the row
- if I add morphs as _"proportionalHeight"_ in an horizontal layout, then the elements' height is proportional _to the row height_ (rather than to each other)

it would seem more logical to me that the second case should behave like the first - height of the elements should be calculated in proportion to all the added morphs rather than only to the height of the container

Example:

```
| pane rect1 rect2 |
pane _ LayoutMorph newRow separation: 5. "1"
pane addMorph: (StringMorph contents: '1').

rect1 := BorderedRectMorph new color: (Color lightOrange);
    layoutSpec: (LayoutSpec  proportionalWidth: 2.0 fixedHeight: 30 minorDirectionPadding: #center).
pane addMorph: rect1.
rect2 := BorderedRectMorph new color: (Color cyan).
pane addMorph: rect2
    layoutSpec: (LayoutSpec  proportionalWidth: 0.5 fixedHeight: 30 minorDirectionPadding: #center).
pane
    color: Color lightGreen;
    openInWorld;
    morphPosition: 320 @ 50;
    morphExtent: 180 @ 100.


pane _ LayoutMorph newRow separation: 5. "2"
pane addMorph: (StringMorph contents: '2').

rect1 := BorderedRectMorph new color: (Color lightOrange).
pane addMorph: rect1 
         layoutSpec: (LayoutSpec  fixedWidth: 20 proportionalHeight: 2.0 minorDirectionPadding: #center).
rect2 := BorderedRectMorph new color: (Color cyan);
    layoutSpec: (LayoutSpec  fixedWidth: 20 proportionalHeight: 0.5 minorDirectionPadding: #center).
pane addMorph: rect2.
pane
    color: Color lightGreen;
    openInWorld;
    morphPosition: 520 @ 50;
    morphExtent: 180 @ 100
```

![screen shot 2014-07-09 at 22 16 28](https://cloud.githubusercontent.com/assets/769568/3531320/5a206156-07ae-11e4-8c48-815e934dba4b.png)

See how in the first case the orange morph is 4 times as big as the other (since proportionalWidth is 2 vs 0.5 of the other morph), which in the second example the height is just such that the orange one is just two times as tall as the row. This can be seen as well resizing both layoutMorphs...

Am I missing something?

**Comment by jvuletich** [comment]
Please email https://lists.cuis.st/mailman/listinfo/cuis-dev if you think this deserves further discussion.
