### ISSUE TITLE
The VM sends scroll wheel events as keyboard arrow keystrokes.

### ISSUE THREAD

**Issue by dhnorton** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#36]
Maybe a better solution would be to just disable keystrokes that modify 
the text, but not others (arrow / scroll wheel, selection and clipboard 
commands, etc).

**Comment by jvuletich** [comment]
Please check with latest updates. It should be fixed.
Please close the issue if now it works ok for you.

**Comment by dhnorton** [comment]
Works OK but I notice first that the test case received DNU concerning #disablekeyboard or some such. After removing that, the test case works on both the old and the new.
