### ISSUE TITLE
Animation Lost in 6129

### ISSUE THREAD

**Issue by KenDickey** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#38]
DisplayObject supplied #slideFrom:to:nSteps:delay: which is used in card animations in Soltiare.

As DisplayObject no longer exists, we need to recreate this functionality.

Ideally, we should do something akin to the W3C SVC spev (See Chapter 19 in http://www.w3.org/TR/SVG11/ ).

**Comment by jvuletich** [comment]
Also, take a close look at Marcel Taeumel's 'Animations':
https://www.hpi.uni-potsdam.de/hirschfeld/trac/SqueakCommunityProjects/wiki/animations
http://map.squeak.org/package/f64a22f8-e16e-459e-8aa0-49f8ac726629
https://github.com/hpi-swa/animations

**Comment by KenDickey** [comment]
Interesting, but seems to be a lot of added code.  I'll have to take a look at this.  

I updated the Animator package in Cuis-Smalltalk-BabySteps to work again in 2198.  I might extend and use that package instead.  Most uses seem simple enough.

More after I have had a chance to digest this and play with working examples.

**Comment by jvuletich** [comment]
Great!

**Comment by KenDickey** [comment]
Solitare now uses CPS (Continuation Passing Style) block closures to structure control flow separate from animation.
