### ISSUE TITLE
Add code snippets to 'Useful expressions' workspace 

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#39]
From ML:

Add examples to 'useful expressions' workspace which show

T1. canonical examples of how to compress/decompress files/streams 

T2. package loading through code. 
 Phil writes "I've been calling CodePackageFile
installFileStream:packageName:fullName: but that no longer appears to be
the correct entry point if I want dependency checking"

**Comment by hhzl** [comment]
Phil writes on the ML

"I started playing around with a couple of example test cases to see what
I ran into and came up with a distinct class to store all of these per
test category (i.e. under Test-Files a class ApiFile which could have a
method testWriteTextFile)  The rationale was that it might make sense to
keep these test cases separate from traditional test cases which are
free to make calls that users of the class (i.e. who are calling the
supported API) should not."

**Comment by hhzl** [comment]
Check if other useful expressions in the workspace still apply.

**Comment by jvuletich** [comment]
The 'Useful Expressions' workspace included this since 2013:
           'Example of loading a package with requirements on other packages'
           Feature require: 'SignalProcessing'.

Just did a few tweaks to other entries there.

**Comment by hhzl** [comment]
Fine, let's then advertise the 'useful expressions' workspace as being updated and **useful**!
