### ISSUE TITLE
OneLineEditorMorph>>disablesEdition required in 2203

### ISSUE THREAD

**Issue by KenDickey** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#44]
Bring up code which uses a OneLineEditorMorph (e.g, package in Cuis-Smalltalk-IA-EN).

Try to use the OneLineEditor instance.

**Comment by jvuletich** [comment]
Fixed in #2206. Please retest.

**Comment by KenDickey** [comment]
On Fri, 06 Mar 2015 04:01:36 -0800
Juan Vuletich <notifications@github.com> wrote:

> Fixed in #2206. Please retest.

# 2203 is the latest image available from GitHub. 

FYI,
-KenD

**Comment by KenDickey** [comment]
Works now.  Thanks much!

**Comment by KenDickey** [comment]
I got some funny behaviors in code I was developing after replacing call to clone w copy (2400).

Simple example:
  Select the code in the PartsBinMorph class comment and DoIt
  Move the PartsBinMorph away from the origin.
  Drag out the oval and note the offset in the copy shares the location.

The solution I have been using is:

MorphIt>>copy
	^self shallowCopy postCopy

MorphIt>>postCopy
	"After a clone or shallow copy, one needs an unshared location"

	location _ MorphicTranslation new

But this has some problems in 2400.

Can you take a look?  

Thanks,
-KenD

**Comment by jvuletich** [comment]
Hi Ken,

On 05/07/2015 12:19 a.m., Ken Dickey wrote:
> I got some funny behaviors in code I was developing after replacing 
> call to clone w copy (2400).
>
> Simple example:
> Select the code in the PartsBinMorph class comment and DoIt
> Move the PartsBinMorph away from the origin.
> Drag out the oval and note the offset in the copy shares the location.
>

I tried this in a fresh Cuis image and found no problem.

Can you give more details?

Cheers,
Juan Vuletich

**Comment by KenDickey** [comment]
Hi Ken,

On 05/07/2015 12:19 a.m., Ken.Dickey wrote:
> I got some funny behaviors in code I was developing after replacing call to clone w copy (2400).
>
> Simple example:
>    Select the code in the PartsBinMorph class comment and DoIt
>    Move the PartsBinMorph away from the origin.
>    Drag out the oval and note the offset in the copy shares the location.

I tried this in a fresh Cuis image and saw no problems.

Can you give more details?

Cheers,
Juan Vuletich

> The solution I have been using is:
>
> MorphIt>>copy
> 	^self shallowCopy postCopy
>
> MorphIt>>postCopy
> 	"After a clone or shallow copy, one needs an unshared location"
>
> 	location _ MorphicTranslation new
>
> But this has some problems in 2400.
>
> Can you take a look?
>
> Thanks,
> -KenD
>

**Comment by KenDickey** [comment]
On Sun, 05 Jul 2015 06:58:10 -0700
Juan Vuletich <notifications@github.com> wrote:

> On 05/07/2015 12:19 a.m., Ken Dickey wrote:
> > I got some funny behaviors in code I was developing after replacing 
> > call to clone w copy (2400).
> >
> > Simple example:
> > Select the code in the PartsBinMorph class comment and DoIt
> > Move the PartsBinMorph away from the origin.
> > Drag out the oval and note the offset in the copy shares the location.

> I tried this in a fresh Cuis image and found no problem.
> 
> Can you give more details?

Yes.  If you don't move the PartsBinMorph away from the origin, the delta will be zero and everything looks fine.

If you move the PartsBinMorph into the center of the screen and drag out the oval, the oval starts out at the screen origin (top left) rather than under the hand.

I see the same thing under both Intel and ARM Linux. 

-- 
-KenD

**Comment by jvuletich** [comment]
Hi Ken,

On 7/5/2015 1:54 PM, Ken Dickey wrote:
> On Sun, 05 Jul 2015 06:58:10 -0700
> Juan Vuletich <notifications@github.com> wrote:
>
> > On 05/07/2015 12:19 a.m., Ken Dickey wrote:
> > > I got some funny behaviors in code I was developing after replacing
> > > call to clone w copy (2400).
> > >
> > > Simple example:
> > > Select the code in the PartsBinMorph class comment and DoIt
> > > Move the PartsBinMorph away from the origin.
> > > Drag out the oval and note the offset in the copy shares the location.
>
> > I tried this in a fresh Cuis image and found no problem.
> >
> > Can you give more details?
>
> Yes. If you don't move the PartsBinMorph away from the origin, the 
> delta will be zero and everything looks fine.
>
> If you move the PartsBinMorph into the center of the screen and drag 
> out the oval, the oval starts out at the screen origin (top left) 
> rather than under the hand.
>
> I see the same thing under both Intel and ARM Linux.

Oh, right! You'd already said it! Apologies. Fix is on GitHub. Thanks 
for reporting.

Cheers,
Juan Vuletich

**Comment by KenDickey** [comment]
On Mon, 06 Jul 2015 06:20:02 -0700
Juan Vuletich <notifications@github.com> wrote:

> Oh, right! You'd already said it! Apologies. Fix is on GitHub. Thanks 
> for reporting.

And thanks exceedingly for the quick fixes!!

 
-KenD
