### ISSUE TITLE
aDictionary asSet

### ISSUE THREAD

**Issue by jvuletich** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#45]
(from an email to the Cuis mail list)

In Squeak, 'someDictionary asSet' answers a set with the values. It should do the same in Cuis, (like Dan and Nicolas want). Maybe we'd also adopt the idea of having HashedCollection as a superclass of both Dictionary and Set, just like in Squeak.

Any takers?

**Comment by dhnorton** [comment]
An #asSet  method for Dictionary could be implemented as:
    ^ self as: Set
which brings a question: in the spirit of Cuis, why not eliminate most of the #asXXX convenience methods, replacing them with the as: Class idiom wherever possible?

**Comment by jvuletich** [comment]
Interesting! I'm not sure if removing them, but at least making them call #as: looks like it makes sense.
