### ISSUE TITLE
NotesOnMorphic.md  -- #step vs. #stepAt:

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#48]
From ML:

On Mon, 2015-03-09 at 05:54 -0400, Phil (list) wrote:

> 1) Morph stepping appears to be non-functional (at least in terms of
> running the code as-is from Cuis 4.0)

Figured this one out... #step appears to be obsolete, use #stepAt:
instead.  In some cases now need to override #wantsSteps to return true
(the default implementation now always returns false.  This is an issue
only for some of my animated morphs.)

**Comment by hhzl** [comment]
Add a slightly extended version of the comment above to 
https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/NotesOnMorphic.md

**Comment by jvuletich** [comment]
This issue has been stagnant for six years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev
