### ISSUE TITLE
NotesOnMorphic.md --- TextModelMorph documentation

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#49]
Juan Vuletich on ML Wed, Jan 28, 2015

_You don't really need a new class. This works:_

```

        model := TextModel new contents: 
                      'Hi folks, \this is a multiline text, \see?' withNewLines .
        doWrap := true.
        m := TextModelMorph withModel: model.
        m wrapFlag: doWrap.
        m hideScrollBarsIndefinitely.
        m lock.
        m openInWorld
```

Things to do
1. Read the complete ML thread which included the creation of change sets.
2. Update the example if necessary
3. Added example to https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/NotesOnMorphic.md

**Comment by jvuletich** [comment]
This issue has been stagnant for six years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev
