### ISSUE TITLE
Clicking on window title grabs window

### ISSUE THREAD

**Issue by bpieber** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#5]
In Cuis 4.2 if you click on a window title the hand grabs the whole window and moves it. You have to click again to let go again. I constantly move windows although I don't want to. This is quite annoying. In Cuis 4.0 the behavior was different.

**Comment by jvuletich** [comment]
I added a new preference #clickGrabsMorphs to control this behavior (it is useful, for example, for touch and pen devices). The default is false, meaning the regular behavior in conventional OSs.
