### ISSUE TITLE
NotesOnMorphic.md -- add remark about the use of #show: deep in Morphic logic

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#50]
From:

J. Vuletich (mail lists)
juanlists@jvuletich.org   Sat, May 9, 2015 at 5:17 PM
To: Pharo Development List pharo-dev@lists.pharo.org

Hi Folks,

(below)

Please take a good look at Cuis' Transcript and consider using it.

By default, the display is updated immediately, but without calling Morphic, it can even work with no UI framework at all. It does updates faster than Squeak or Visualworks:

```
    Time millisecondsToRun: [ 1000 timesRepeat:  [ Transcript show: 'x' ] ]. 763.
```

But if you want minimum overhead without immediate feedback:

```
    Time millisecondsToRun: [ Transcript showOnDisplay: false. 1000 timesRepeat:  [ Transcript show: 'x' ]. Transcript showOnDisplay: true ]. 1.
    "As fast as Pharo"
```

It is also thread safe, and for Ben's example:

Transcript clear.
[
        $a asciiValue to: $z asciiValue do: [ :c |
                [ 1 to: 9 do: [ :i | Transcript show: c asCharacter printString , i printString , ' ' ] ] forkAt: 40
        ].
] forkAt: 41

it gives the same result as Pharo.

The fact that the updates are not bound to Morphic also means that it is possible to do #show: deep in Morphic logic, without causing infinite loops or recursions, and get immediate feedback. It has proved to be a useful aid in debugging Morphic code.

**Comment by jvuletich** [comment]
This issue has been stagnant for six years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev
