### ISSUE TITLE
NotesOnCuis.md  --- New image format: Cog format

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#54]
J. Vuletich (mail lists)
juanlists@jvuletich.org   Wed, May 13, 2015 at 2:08 PM
Reply-To: juan@jvuletich.org, Pharo Development List pharo-dev@lists.pharo.org
To: Pharo Development List pharo-dev@lists.pharo.org,

The Cuis image is now in Cog format (6505) instead of Closures format (6504). I hope this allows you to run Cuis in your system.

Clarify in README.md

**Comment by jvuletich** [comment]
Time has shown this to be inconsequential. I see no issue. Should we close it?

**Comment by hhzl** [comment]
I suggest to add it in ``NotesOnCuis.md``. I suggest to keep the issue open until we wrap up a number of things in this file in one go.

**Comment by hhzl** [comment]
See *https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/ImageFormatsAndVMs.md*
