### ISSUE TITLE
Add to documentation -- notes about preferences

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#56]
If you want to show all underscores as such (ASCII69, Unicode, most modern systems), everywhere, evaluate:

```
     StrikeFont useUnderscore
```

If you want to get left arrows (ASCII63, classic ST-80), evaluate:

```
   StrikeFont useLeftArrow
```

Maybe you also want to see variable assignment as `:=` . For this evaluate:

```
  Preferences enable: #syntaxHighlightingAsYouTypeAnsiAssignment
```

Note: By default, Cuis accepts underscores as assignment, and also as part of selectors and variable names. This works independently of the choice of the glyph to be shown. There are also preferences for controlling this.

**Comment by jvuletich** [comment]
This issue has been stagnant for six years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev
