### ISSUE TITLE
Add explanation and version information to CompatibilityPackages folder

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#57]
Juan on ML Tue, May 19, 2015

The ``CompatibilityPackages``  folder is for ``SqueakCompatibility.pck.st``, and any other packages that depend on it. ``VMMaker``, for instance, is a verbatim copy of **current** (i.e. May 2015) VMMaker for Squeak, without a single line of code changed. But this is open for discussion.

Add reference to source (including version number) of ``VMMaker``

**Comment by jvuletich** [comment]
Yes, that is important. Just did it.

**Comment by hhzl** [comment]
Yes, and what about Balloon?
