### ISSUE TITLE
Character unicodeCodePoint: 164 gives wrong result

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#58]
According to 
      http://www.fileformat.info/info/unicode/char/a4/index.htm

The expression 

     Character unicodeCodePoint: 164 

should evaluate to the Euro symbol. But instead it evaluates to ``nil``.

**Comment by jvuletich** [comment]
Nope. According to

    http://www.fileformat.info/info/unicode/char/a4/index.htm ,

the expression

    Character unicodeCodePoint: 164 

should evaluate to the currency symbol. But that character is not in the ISO 8859-15 character set Cuis uses. But also according to

    http://www.fileformat.info/info/unicode/char/20a0/index.htm

the expression

    Character unicodeCodePoint: 8364

should evaluate to the Euro sign, as it does.
