### ISSUE TITLE
Expected failures in SUnit

### ISSUE THREAD

**Issue by bpieber** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#6]
Squeak and Pharo allow to specify expected failures in SUnit tests. An expected failure is green when it fails and red when it succeeds. This is very convenient for bugs that cannot be fixed easily. It allows to ship a release with all tests green.

Compatibility with the Squeak and Pharo implementation would be good to easy porting.

**Comment by jvuletich** [comment]
If you feel this deserves further discussion, please email https://lists.cuis.st/mailman/listinfo/cuis-dev
