### ISSUE TITLE
copyImage.sh has reference to past image

### ISSUE THREAD

**Issue by ThierryGoubier** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#60]
Hi,

bin/copyImage.sh tries to copy Cuis4.2-2203, whereas current version is Cuis4.2-2336.

**Comment by jvuletich** [comment]
I updated the references.

**Comment by ThierryGoubier** [comment]
Thanks!

Thierry

2015-05-28 14:21 GMT+02:00 Juan Vuletich <notifications@github.com>:
