### ISSUE TITLE
Documentation: Changes in Morph step behaviour between Cuis 4.0 and Cuis 4.2

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#65]
Phil writes on the ML:
# Morphic (continuous) animation

previously: (4.0)

```
#step
```

now: (since 4.2)

```
#stepAt: 
```

(just rename #step to #stepAt: milliseconds)

```
#wantsSteps (^true)
```

Notes:

1) If this change isn't made, you may get what appears to be animation,
but it's just the morph redrawing after damage.
2) Be sure to call #truncate on bounds etc. if your code can't handle
floats.
3) I used to have several direct Morph subclasses, but it appears that
they now need to be RectangleLikeMorph subclasses to maintain similar
behavior.
# Keyboard focus handling

previously:

```
#handlesKeyboard 
    (^ true)

 #keyboardFocusChange: 
    "(call any code needed to deal with getting/losing
    focus such as drawing a focus indicator)"


  #handleKeystroke: 
    "(when morph has focus, will receive keystroke)"
```

now:

This is my best guess... are there any examples of working Morphs that
deal with keyboard focus but do _not_ have text morphs?

```
#handlesKeyboard (no change)

#handlesMouseOver: 

    (^true to get #mouseEnter: & #mouseLeave:)


#mouseEnter: event
    event hand newKeyboardFocus: self

#mouseLeave: event
    event hand newKeyboardFocus: nil

#keyStroke: event 
    "(receives the keystroke when focused, some event accessors no longer exist)"
```

One additional thing related to keyboard focus that should probably be
handled by Morphic: various mouse (mouse wheel) and trackpad (gesture)
events get sent as keyboard events and should probably be (at least
optionally?) intercepted from the event stream and sent as distinct
events such as #scroll: etc.  No idea how multi-finger touch screen
gestures are handled by the VM these days but that is yet something else
to think about...

**Comment by jvuletich** [comment]
I don't think this describes any issue to be addressed.
