### ISSUE TITLE
Documentation: assignment substitution?   Underscore?

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#67]
On 7/15/2015 8:43 PM, Phil (list) wrote:

```
Is there a setting that will disable this substitution?  I would
actually prefer it to go the other way: if it sees an _ assignment,
replace it with :=
```

JV answered.

Please check #syntaxHighlightingAsYouTypeAnsiAssignment and #syntaxHighlightingAsYouTypeLeftArrowAssignment . Both default to false.

Would turning on #syntaxHighlightingAsYouTypeAnsiAssignment be enough for you?

Update FAQ entry or note

**Comment by hhzl** [comment]
Phil on ML

I'm already setting #syntaxHighlightingAsYouTypeAnsiAssignment to true
and leaving #syntaxHighlightingAsYouTypeLeftArrowAssignment at false.
That seems to work for everything except pretty printing.  I also played
with #allowUnderscoreAssignments but that just determines whether or not
_ is valid and doesn't stop pretty print trying to use underscores
anyway (which is entertaining because then pp produces invalid code :-)

**Comment by jvuletich** [comment]
Is it working correctly now? If so, please close the issue. If not, please give more details on how to reproduce problems.
