### ISSUE TITLE
Make list headers in CodePackageListWindow adjust to Morph height (discovered when using Large Fonts) Raw

### ISSUE THREAD

**Issue by duncanmak** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#72]
Hello @jvuletich,

I'm at Camp Smalltalk with @KenDickey and we discovered that the headers in `CodePackageListWindow` clips when using the Very Large font setting.

We made a small changeset to fix this, but we also see that a similar issue can be found in the ChangeSet editor.

https://gist.github.com/duncanmak/a45114d653fd66828c3c

**Comment by duncanmak** [comment]
I just refreshed the patch to add the same fix to the `ChangeSorterWindow` as well as `CodePackageListWindow`.

**Comment by jvuletich** [comment]
Thanks Duncan and Ken!
This will be in the next commit to the repo.
