### ISSUE TITLE
DOC: Add note about Sound

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#82]
Add a note like:

Cuis has the Sound system of Squeak in  Package.

Load it with 

```
   Feature require: 'Sound'.
```

Then play a melody with:

```
    (AbstractSound noteSequenceOn: 
              PluckedSound default from: 
                          #((c4 1 500) 
                             (d4 1 500) 
                             (e4 1 500) 
                             (g4 1 500) 
                             (a4 1 250)
                             (a4 1 250) 
                             (c5 1 500)
                           )
               ) play
```

More: 
http://wiki.squeak.org/squeak/152

**Comment by hhzl** [comment]
Another example which produces a WAV file

    (AbstractSound noteSequenceOn: FMSound flute2 from: #(
    (e5 0.5 500)
    (d5 0.5 300)
    (c5 0.5 350)
    (d5 0.5 300)
    (e5 0.5 500)
    (e5 0.5 300)
    (e5 1.0 350)
    (d5 0.5 400)
    (d5 0.5 300)
    (d5 1.0 330)
    (e5 0.5 400)
    (g5 0.5 300)
    (g5 1.0 500)
    )) storeWAVOnFileNamed: 'maryhadalittlelamb.wav'

Source: http://wiki.squeak.org/squeak/2125

**Comment by jvuletich** [comment]
This issue has been stagnant for five years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev

**Comment by nmingotti** [comment]
i added hhzl notes about sound in the latest version of the CuisCookBook, here: 
http://cuiscookbook.euriscom.it/mediawiki/index.php/The_Cuis_Cookbook

**Comment by nmingotti** [comment]
hi @stephensmith9 , I wrote the procedure to become editor [here](http://95.179.246.60/mediawiki/index.php/Contributions_motivated_guidelines) . Please follow it, just to check it is all clear. I actually already enabled your user to be editor.

**Comment by hhzl** [comment]
Hi Stephen
there is now a collection of central repositories for Cuis documentation.

For a HowTo about sound: It would go into the wiki of
https://github.com/DrCuis/Technical
and when finished go into the repository signed with your name.

**Comment by hhzl** [comment]
https://github.com/DrCuis/Technical/wiki/How-to-use-sound

**Comment by hhzl** [comment]
@stephensmith9
  
Stephen, if you like to write about sound in Cuis you might also just fork https://github.com/DrCuis/Technical copy what I have collected under https://github.com/DrCuis/Technical/wiki/How-to-use-sound and issue a pull request.

The Squeak wiki has a lot of examples to be lifted out and be rewritten for Cuis (the sound package is the same). But better organization of the content would be welcome.

http://wiki.squeak.org/squeak/2125
http://wiki.squeak.org/squeak/1952

**Comment by stephensmith9** [comment]
> hi [@stephensmith9](https://github.com/stephensmith9) , I wrote the procedure to become editor [here](http://95.179.246.60/mediawiki/index.php/Contributions_motivated_guidelines) . Please follow it, just to check it is all clear. I actually already enabled your user to be editor.

Thank you @nmingotti and I will respect your policies.
