### ISSUE TITLE
DOC: Review and update notes on Unicode support

### ISSUE THREAD

**Issue by hhzl** [Cuis-Smalltalk/Cuis-Smalltalk-Dev#84]
This https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/commit/2b02227541ec34fbfc9bf1f70069df66e664b9fd commit added 32 mathematical symbols.

Review and update Unicode notes

https://github.com/Cuis-Smalltalk/Cuis-Smalltalk-Dev/blob/master/Documentation/UnicodeNotes.md

to describe current status.

**Comment by hhzl** [comment]
Juan Vuletich<juan@jvuletich.org>	Fri, Dec 4, 2015 at 2:32 PM to mailing list

Current status of Cuis Unicode support:

1) Limited Unicode support (as in Cuis). Can handle Unicode character in Strings. Comfortable Display / edit of text is restricted to Latin alphabet. Non ISO-8859-15 characters are represented as NCRs, but are not instances of Character themselves. For example, an NCR such as '&#945;' (made of 5 8-bit Characters) represents the greek letter Alpha, and is properly handled if such string is converted to an UTF-8 ByteArray (for example for copying into the Clipboard or for serving Web pages). In short, you can not directly edit or display general Unicode, but you can embed it in code, include it in Strings, copy&paste, and serve web pages with it.

2) Ken's Cuis-Smalltalk-Unicode. Can display and edit. Includes the great Ropes representation for Strings. Limited font support.

**Comment by hhzl** [comment]
Explain  the function of #initializeUnicodeCodePoints

**Comment by hhzl** [comment]
http://utf8everywhere.org/
(7)
By design of this encoding, UTF-8 guarantees that an ASCII character value or a substring will never match a part of a multi-byte encoded character.
....
Also, you can search for a non-ASCII, UTF-8 encoded substring in a UTF-8 string as if it was a plain byte array—there is no need to mind code point boundaries. This is thanks to another design feature of UTF-8—a leading byte of an encoded code point can never hold value corresponding to one of trailing bytes of any other code point.

(10)
Always produce text output files in UTF-8.

**Comment by hhzl** [comment]
Code conversion

Squeak

     (UTF8TextConverter new encodeString: 'Les élèves Français') asByteArray 

     #[76 101 115 32 195 169 108 195 168 118 101 115 32 70 114 97 110 195 167 97 105 115]

Pharo

    'Les élèves Français' utf8Encoded
    #[76 101 115 32 195 169 108 195 168 118 101 115 32 70 114 97 110 195 167 97 105 115]
 

$é is encoded in ISO-9959-1 as #[233], but as #[195 169] in UTF-8.

**Comment by hhzl** [comment]
Class Unicode in Squeak and Pharo
http://wiki.squeak.org/squeak/6225

**Comment by jvuletich** [comment]
This issue has been stagnant for five years. If you think further action is in order, please discuss at https://lists.cuis.st/mailman/listinfo/cuis-dev
